heroku/heroku-connect-plugin

- lib/commands/connect/export.js
- lib/commands/connect/import.js
- lib/commands/connect/info.js
- lib/commands/connect/mapping-create.js
- lib/commands/connect/mapping-delete.js
- lib/commands/connect/mapping-state.js
- lib/commands/connect/pause.js
- lib/commands/connect/restart.js
- lib/commands/connect/resume.js
- lib/commands/connect/setup.js
- lib/commands/connect/state.js
I believe we added this before the toolbelt added its own `--remote`/`-r` flag. We can still use `--resource`, but competing usage of `-r` is a bad idea.
> Remove -r flags, which conflict with --remote

- lib/commands/connect/shared.js
- package.json
`co` does a better job at promises, and happens to be the recommended best practice from the Heroku Toolbelt plugin development docs.
> Remove Q as a dependency

- package.json
This is probably nice to have anyway, but in particular npm kept issuing warnings because it wasn't present. Now those warnings can go away.
> Add a repository URL to package.json

- lib/commands/connect/shared.js
“let” isn’t as forgiving as “var”, so this didn’t work right. Now it does.
> Fix scope for the addon variable

- lib/commands/connect/shared.js
Win one for centralized libraries! Also, I don't know if we'll need to add a `dev-herokuconnect-us.herokuapp.com` at some point as well, but it doesn't exist today, so we can revisit later if/when we decide to go that route.
> Update to connect-us.heroku.com

- lib/commands/connect/shared.js
When trying to do connection:info in our testing, the tests fail because
$HOME/.heroku does not exist. This is a temporary workaround for that
issue.
> Hot-fix for production-eu tests

- commands/connect/db-set.js
- commands/connect/diagnose.js
- commands/connect/export.js
- commands/connect/import.js
- commands/connect/info.js
- commands/connect/mapping-delete.js
- commands/connect/mapping-diagnose.js
- commands/connect/mapping-reload.js
- commands/connect/mapping-state.js
- commands/connect/pause.js
- commands/connect/restart.js
- commands/connect/resume.js
- commands/connect/sf-auth.js
- commands/connect/state.js
- lib/connect/regions.js
The `--region` flag still reigns supreme, if supplied, but the default now fetches the region from the app instead. Better yet, it only fetches from the app if the `--region` flag isn't supplied. So this should allow 99% of users to use the CLI without the `--region` flag, while still giving a backdoor for those who need it.
Using the Heroku API required making `determineRegion` asynchronous, which in turn requires a different way to call it (in addition to needing to pass in the Heroku API client). So there are a lot of files changed, but most of them are just a simple usage change.
I also reorganized `determineRegions` a bit and simplified it. Checking for `--region` first not only saves us an API call in some isolated cases, it also makes the `if` read as a positive, rather than a …
> Automatically detect region via the app

- commands/connect/diagnose.js
Only log warnings and errors and only display information about mappings
if there are warnings and errors to show.
> Add --verbose/-v flag to connect:diagnose

- README.md
- lib/connect/api.js
- package.json
- test/commands/connect/state.js
The old name is Toolbelt and the new name is CLI, according to https://devcenter.heroku.com/articles/heroku-cli
> Replace Toolbelt with CLI

- commands/connect/diagnose.js
- commands/connect/mapping-diagnose.js
- package.json
This adds a new grouping for skipped results and also fixes a bug that prevented `connect:mapping:diagnose` from working properly.
It shouldn't be published on npm until the API changes in https://github.com/heroku/herokuconnect/pull/5393 get deployed.
Refs https://github.com/heroku/herokuconnect/issues/5376
> Categorize skipped results in connect:diagnose output

- lib/connect/api.js
- test/commands/connect/sf-auth.js
- test/commands/connect/state.js
Our connection list endpoint can already accept `resource_name` directly as a search term, so we don't actually need to first lookup the resource ID from the platform API. We're using this as our main entry point into the API, so this should save us an API call pretty much across the board. If `--resource` isn't provided, the API call will supply an empty value, which will simply not get added to the query.
> Simplify --resource lookup

- commands/connect/mapping-write-errors.js
- index.js
This allows customers to retrieve write errors from the API as a
proof-of-concept of how to view write-errors not in the dashboard and
not via PSQL
> POC: Add connect:mapping:write-errors

- commands/connect/mapping-write-errors.js
- commands/connect/state.js
The output looks like:
```
❯❯❯ heroku connect:state -a a-test-connect-app
Database      Schema      State
────────────  ──────────  ─────
DATABASE_URL  salesforce  IDLE
```
This also removes `printHeader` in `mapping:write-errors` as it's
apparently an invalid option.
> Fix showing connection state for all connections on an app

- commands/connect/sf-auth.js
- test/commands/connect/sf-auth.js
Apparently this feature was never implemented into the API and
does not serve any purpose.
> Fix #85 -- Remove --login flag from sf:auth command

- commands/connect/sf-auth.js
The API does support multiple environents and even custom domains.
This feature this feature can be particularly helpful for
developers since they are more likely to connect often create new
connections to sandboxes as they are to a production environemnt.
Please see:
https://devcenter.heroku.com/articles/heroku-connect-api#step-6-authenticate-the-connection-to-your-salesforce-org
4251209
> Add environment and domain flag for sf:auth command

- lib/connect/regions.js
- package.json
- test/commands/connect/state.js
They were outdated and causing us to see odd bugs that should never have manfiested, e.g., heroku/heroku-pg#188 
As a result, we need to update a little bit of our code around using the node client for heroku
> Update plugin dependencies

- commands/connect/recover.js
- index.js
This better matches what the Connect dashboard shows users who need the
same functionality. Also "restart" sounds a bit more destructive than
recover actually is.
> Rename restart to recover

- commands/connect/db-set.js
Inquirer changed its API to rely on Promises. Now, when we create a
prompt, we only pass the choices, and receive the answers as a promise.
This updates connect:db:set to rely on that new API.
Closes gh-92
> Fix bug introduced by upgrading inquirer

- commands/connect/info.js
- test/commands/connect/info.js
As per user feedback, the error message from the `connect:info` command can be confusing if the user hasn't yet `addons:open`ed that particular connection.
This PR updates the error message of `connect:info` with a helpful command that should at least get users on the right track.
> Improve Error Message of connect:info Command

- commands/connect-events/info.js
- commands/connect/info.js
- lib/clients/discovery.js
- lib/connect/api.js
- test/commands/connect/info.js
This functionality got pulled out when the discovery service was added because we didn't have an equivalent endpoint in the discovery service. This PR brings back that behavior. See [this line](https://github.com/heroku/heroku-connect-plugin/pull/99/files#diff-a541cf0e44c990d4833aa61573da7d5dL25) for the removal of the original behavior.
> Add back ability to check for access to addons without addons:open

- commands/connect/diagnose.js
- test/commands/connect/diagnose.js
This PR closes https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000007bT6rIAE/view.
It updates `connect:diagnose` to use the new asynchronous endpoint for connection validations.
> Make `connect:diagnose` poll for results

- README.md
This mainly fixes the installation instructions to point to the new package location of `@heroku-cli/heroku-connect-plugin`. It also updates the structure of the markdown
> Fix installation instructions, update structure of markdown
