lib/commands/connect/shared.js
Corrects usage of the Authorization header and adds a Heroku-Client
header, to identify it a Heroku-published utility.
=> Fix HTTP headers

index.js, lib/commands/connect/info.js
This should help avoid confusion between connect:status and connect:state
=> Rename connect:status to connect:info

lib/commands/connect/export.js, lib/commands/connect/import.js, lib/commands/connect/shared.js
This also simplifies the commands by using the existing `api.withConnection` function to specify a single connection.
=> Update import and export to use co blocks

lib/commands/connect/mapping-json.js, lib/commands/connect/shared.js
This also adds a helper for fetching a single mapping, which will be useful as we flesh out additional mapping commands.
=> use co blocks in connect:mapping:json

lib/commands/connect/state.js
For consistency, and also to properly handle resource ID lookups by passing in the heroku client.
=> Use cli.command for connect:state

lib/commands/connect/pause.js, lib/commands/connect/resume.js
I'm likely going to try to centralize how we handle things like 409, but until I do that, it'll stay here for now.
=> Use co blocks for pause and resume operations

lib/commands/connect/mapping-create.js, lib/commands/connect/mapping-delete.js, lib/commands/connect/mapping-json.js, lib/commands/connect/mapping-state.js, lib/commands/connect/pause.js, lib/commands/connect/restart.js, lib/commands/connect/resume.js, lib/commands/connect/setup.js, lib/commands/connect/shared.js, lib/commands/connect/state.js
=> Use let instead of var

lib/commands/connect/export.js, lib/commands/connect/import.js, lib/commands/connect/info.js, lib/commands/connect/pause.js, lib/commands/connect/restart.js, lib/commands/connect/resume.js, lib/commands/connect/setup.js, lib/commands/connect/shared.js, lib/commands/connect/state.js
Standardize on 2-space indents throughout various commands
=> Cleanup indents

README.md, index.js, lib/commands/connect/sf-auth.js
This better segments the Salesforce behavior into a namespace that can be reused for more features later on.
=> Change connect:auth to connect:sf:auth

lib/commands/connect/export.js, lib/commands/connect/import.js, lib/commands/connect/mapping-delete.js, lib/commands/connect/mapping-reload.js, lib/commands/connect/pause.js, lib/commands/connect/restart.js, lib/commands/connect/resume.js, lib/commands/connect/sf-auth.js, lib/commands/connect/shared.js
Connects to heroku/herokuconnect#2612
=> Cli action

lib/commands/connect/sf-auth.js
Connects to heroku/herokuconnect#2612
=> Refactor sf:auth to use cli.action

lib/commands/connect/shared.js
This was why the Direwolf QA EU test runs were failing.
=> Update qa eu hostname

lib/commands/connect/shared.js
=> switch qa-frankfurt to qa-dublin

lib/commands/connect/shared.js, package.json
Update the version so we can quickly release this to attempt to unbreak our CI.
=> Skip directory creation if it isn't necessary

lib/commands/connect/db-set.js, lib/commands/connect/export.js, lib/commands/connect/import.js, lib/commands/connect/info.js, lib/commands/connect/mapping-delete.js, lib/commands/connect/mapping-reload.js, lib/commands/connect/mapping-state.js, lib/commands/connect/pause.js, lib/commands/connect/regions.js, lib/commands/connect/restart.js, lib/commands/connect/resume.js, lib/commands/connect/sf-auth.js, lib/commands/connect/shared.js, lib/commands/connect/state.js
=> Add understanding of --region flag to connect subcommands

commands/connect/diagnose.js, commands/connect/mapping-diagnose.js, index.js, lib/connect/api.js
In retrospect, I probably should've put the two commands in separate PRs, but the mapping one is pretty much just a copy/paste of the connection command, but with mapping-specific bits copied from our other mapping commands.
=> connect:diagnose and connect:mapping:diagnose

lib/connect/api.js, lib/connect/regions.js
This also rips out our old US/EU handling code, which wasn't actually useful anymore anyway.
=> Support the QA addon in our new region lookups

commands/connect/write-errors.js, index.js, lib/connect/api.js
Also color the message about no write errors to be green and positive.
=> Add support for connect:write-errors

package.json
Changelog:
```
* Rename restart to recover (#89)
* Add environment and domain flag for sf:auth command (#87)
* Remove --login flag from sf:auth command (#85)
```
=> Release version 0.6.0

commands/connect/mapping-delete.js, commands/connect/mapping-diagnose.js, commands/connect/mapping-reload.js, commands/connect/mapping-state.js, commands/connect/mapping-write-errors.js, index.js
This allows those subcommands to be properly grouped when viewing help
output.
=> Add connect:mapping as another topic

commands/connect/db-set.js, lib/clients/discovery.js
Also be resilient to not having an addon plan when doing db provision
Closes: #106
=> Support dev server

lib/connect/api.js, package.json, test/lib/connect/api.js, test/mocha.opts, yarn.lock
Notes
--------
Make sure the object_name is a complete match instead of starts with.
Links
-------
- [Work Item](https://gus.my.salesforce.com/a07AH000000ORO4YAO)
=> Full Name Match

.github/dependabot.yml, CODEOWNERS, CONTRIBUTING.md, LICENSE.md, SECURITY.md, package.json
Updated the project name in package.json to properly note the @heroku-cli org.
Also added CODEOWNERS, CONTRIBUTORS, LICENSE, SECURITY, and dependabot.yml files. These are items in the GitHub Maintenance tasks for the Baseline Processes Optimization epic.
[W-12338106](https://gus.lightning.force.com/lightning/r/a07EE00001IodPzYAJ/view)
https://salesforce.quip.com/Rf58AQg13k6u
=> Repo maintenance

commands/connect/diagnose.js, lib/clients/discovery.js, test/commands/connect/sf-auth.js
This PR updates the linting after updating `standard` dependency.
=> Update linting after updating standard dependency

package.json
Bump to `v0.11.1` post linting update.
=> Bump to v0.11.1

package.json, yarn.lock
This PR updates the `cross-spawn` transitive dependency to a non-vulnerable version as well as the `brace-expansion` low vulnerability.
**Notes**: N/A
Passing CI
Gus Work Item: [W-19111805](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00002Il2LIYAZ/view) (Heroku internal)
=> fix: update transitive dependency to fix high vuln
